{% set name = "xesn" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xesn-{{ version }}.tar.gz
  sha256: 6a9ff582b9d4e9eb3a2c5742e8b3ef002ff5d2095d1db0410e58a4c2708c71c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - xarray
    - dask-core
    - zarr
    - smt >=2.2.1
    - matplotlib-base

test:
  imports:
    - xesn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timothyas/xesn
  summary: Echo State Networks powered by xarray
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://xesn.readthedocs.io
  dev_url: https://github.com/timothyas/xesn


extra:
  recipe-maintainers:
    - timothyas
